APP-761: MessageMLv1 parsers and unit tests refactored to reflect new MessageMLv2 package structures.
SymphonyOSF/App-Integrations-Github pull request #28
Opened 2017-05-04 18:45 UTC by campidelli

MessageMLv1 parsers and unit tests refactored to reflect new MessageMLv2 package structures.

2017-05-05 13:36 UTC, robson-sanchez requested changes
Small changes.

2017-05-05 13:36 UTC, robson-sanchez commented on src/main/java/org/symphonyoss/integration/webhook/github/GithubWebHookIntegration.java
> +    supportedContentTypes.add(MediaType.WILDCARD_TYPE);
I believe we should keep the MediaType.APPLICATION_JSON_TYPE, because for while the only supported content type is 'application/json'

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/BaseDeploymentGithubParser.java
> +      return entityML;
The variable entityML isn't required, you might return directly.

Like this: return buildEntityML(node);

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/CommitCommentGithubParser.java
> +      return entityML;
Same comment above

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/IssueCommentGithubParser.java
> +      String entityML = buildEntityML(node);
You might return directly.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/PublicGithubParser.java
> +      return entityML;
You might return directly.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/PullRequestGithubParser.java
> +      return entityML;
You might return directly.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/PullRequestReviewCommentGithubParser.java
> +      return entityML;
You might return directly.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/PushGithubParser.java
> +      return entityML;
You might return directly.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/ReleaseGithubParser.java
> +      return entityML;
You might return directly.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/StatusGithubParser.java
> +      return entityML;
You might return directly.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v2/GithubMetadataParser.java
> +  private String integrationUser;
This field might be protected to be reused in all the subclasses.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v2/GithubPushMetadataParser.java
> +  public void setIntegrationUser(String integrationUser) {
This method should be implemented in the superclass.

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v2/GithubPushMetadataParser.java
> +  }
This method shouldn't be implemented here. You should only implement the methods preProcessInputData (optional),  postProcessOutputData (optional), getTemplateFile(), and getMetadataFile().

2017-05-05 13:36 UTC, rsanchez-daitan commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/GithubParserFactory.java
> +      LOGGER.debug("Unhandled event {}", eventName);
You should perform the logging inside the NullGitHubParser. Perhaps you can also add more information to simplify our troubleshooting and increase the log level to INFO.

2017-05-19 19:23 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/GithubWebHookIntegration.java
> +    supportedContentTypes.add(MediaType.WILDCARD_TYPE);
Done.

2017-05-19 19:23 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/BaseDeploymentGithubParser.java
> +      return entityML;
Done.

2017-05-19 19:23 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/CommitCommentGithubParser.java
> +      return entityML;
Done.

2017-05-19 19:23 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/IssueCommentGithubParser.java
> +      String entityML = buildEntityML(node);
Done.

2017-05-19 19:23 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/PublicGithubParser.java
> +      return entityML;
Done.

2017-05-19 19:23 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/PullRequestReviewCommentGithubParser.java
> +      return entityML;
Done.

2017-05-19 19:24 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/PushGithubParser.java
> +      return entityML;
Done.

2017-05-19 19:24 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/ReleaseGithubParser.java
> +      return entityML;
Done.

2017-05-19 19:24 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v1/StatusGithubParser.java
> +      return entityML;
Done.

2017-05-19 19:25 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v2/GithubMetadataParser.java
> +  private String integrationUser;
Done.

2017-05-19 19:26 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v2/GithubPushMetadataParser.java
> +  public void setIntegrationUser(String integrationUser) {
Why? The super class doesn't implement the interface that defines this method.

2017-05-19 19:27 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/v2/GithubPushMetadataParser.java
> +  }
It's no longer there.

2017-05-19 19:29 UTC, campidelli commented on src/main/java/org/symphonyoss/integration/webhook/github/parser/GithubParserFactory.java
> +      LOGGER.debug("Unhandled event {}", eventName);
Log level changed to INFO.

2017-05-22 11:36 UTC, rsanchez-daitan commented
This PR is being closed because this code was included on the PR #29.

2017-05-22 11:36 UTC, closed without merging