APP-960: New version of Readme.MD
SymphonyOSF/App-Integrations-Github pull request #30
Opened 2017-05-25 22:59 UTC by campidelli

Contains only information about MessageMLv2 and only one event as example.

2017-05-25 23:14 UTC, vincentmg commented
Updated the readme a bit more. Please take a look @campidelli  @ecarrenho-daitan

2017-05-26 18:46 UTC, robson-sanchez requested changes
Really good :+1:

Just take a look at the comment regarding the event list.

2017-05-26 18:46 UTC, rsanchez-daitan commented on README.md
> +Every integration will receive a [message](#github-json-message-sent-check-it) sent in a specific format (depending on the system it ingests) and will usually convert it into an object called **Messa
The 'message' link isn't working.

2017-05-26 18:46 UTC, rsanchez-daitan commented on README.md
> +Currently we support the following ten events from GitHub:
I think we left the event 'Create a branch or tag' in this list.

2017-05-26 18:58 UTC, campidelli commented on README.md
> +Every integration will receive a [message](#github-json-message-sent-check-it) sent in a specific format (depending on the system it ingests) and will usually convert it into an object called **Messa
Done.

2017-05-26 18:59 UTC, campidelli commented on README.md
> +Currently we support the following ten events from GitHub:
Done.

2017-05-26 19:01 UTC, robson-sanchez approved these changes

2017-05-26 19:02 UTC, merged